Red Licorice https://www.holotaco.com/products/red-licorice;
Coral Chaser https://www.holotaco.com/products/coral-chaser;
Naughty List **limited edition**;
Party Punch https://www.holotaco.com/products/party-punch;
Play Rose https://www.holotaco.com/products/play-rose;
Fake Date https://www.holotaco.com/products/fake-date;
Cats Evasion https://www.holotaco.com/products/cats-evasion;
Left on Red https://www.holotaco.com/products/left-on-red;
The Floor is Guava https://www.holotaco.com/products/the-floor-is-guava;
One Melon Followers https://www.holotaco.com/products/one-melon-followers;
Solar Unicorn Skin https://www.holotaco.com/products/solar-unicorn-skin;
Polar Princess https://www.holotaco.com/products/polar-princess;
